### ISSUE TITLE
Update website and clean up repository

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb.github.io#3]
Hi,

I don't know if you already checked that, but KairosDB website and repository have a lot of problems:

* The new website (website/index.html) is not the default and the old one is better ranked on Google, so you're showing a ugly website for almost all (possible new) users of KairosDB. 
* The new website have links pointing to the old, including in it's documentation.
* The repo is disorganized and contains old code in the master branch.
* etc.

I've forked the repository and made some modifications on the forked repo: https://github.com/paladini/kairosdb.github.io. **What I've done:**

* Created a branch called "beta", for the "beta" folder and its contents. Cleaned up files that isn't related with this version of the website.
* Created a branch called "old", for the current master branch of this project. 
* Cleaned up everything and made "website/" the default site for this project. 

Now I think it's well designed, but as Github doesn't support "pull requests" to create other branches (I just can make a pull request for master branch), I would like to ask to be added to the list of users that can Push to this repository. If you can't do that, please take a look at my repository and reorganize your repo based on mine (would be nice and will fix a lot of issues with your website).

**Comment by at15** [comment]
:+1: the old website caused me a lot of trouble finding the download section ....

**Comment by paladini** [comment]
Done!
