### ISSUE TITLE
Add instructions on how to add documentation

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb.github.io#5]
I would like to know how I can made modifications or create new docs for the KairosDB documentation. I see that you use Sphinx documentation generator, but I don't know how to proceed.

A README.md explaining that would be nice.

**Comment by brianhks** [comment]
Yes a readme would be good.  Here are the basics, the docs are built frome the Kairosdb project.
1.  Install python-sphinx - the build uses sphinx-build
2.  Run: 'java make docs' to generate, have a look at the how_to_build.txt file in the karios project.

**Comment by paladini** [comment]
Done! I've made a wiki page for this topic on the KairosDB core project at Github.

https://github.com/kairosdb/kairosdb/wiki/Contribute:-Documentation
