### ISSUE TITLE
Kairosdb.org redirecting to "kairosdb.github.io/website/index.html"

### ISSUE THREAD

**Issue by paladini** [kairosdb/kairosdb.github.io#6]
As you can see [here](https://github.com/kairosdb/kairosdb.github.io/commit/1e0e60ac36396163f3547612dea14148f1339681), I've made a temporary page that redirects from "kairosdb.github.io/website/" to "kairosdb.github.io", the new home for our website.

The problem is that kairosdb.org still redirecting all users to "kairosdb.github.io/website/index.html" and it should be fixed ASAP (for Search Engine Optimization reasons). As I don't have access to domain name provider, I can't do that by myself. 

Anyway, after that I think we can remove the temporary file at "/website/index.html".

**Comment by brianhks** [comment]
Awesome, thanks.  I've fixed the domain name to not go to /website.
